In [80]:
import pandas as pd
df = pd.read_excel(r"Oracle Employee Report 26-Jun-2017.xlsx")
df.columns = df.columns.str.replace(' ', '_')

In [ ]:
df.Care

In [79]:
df = df[(df.Payroll_Country.isin(['United States'])) & df.Career_Band.isin(['Supervisor / Management'])]

AttributeError: 'DataFrame' object has no attribute 'Payroll_Country'

In [29]:
df = df[['Job_Code','Career_Level', 'Employee_Birth_Date'
   ,'Salary_Change_%','Annual_Salary_If_Full_time'
   , 'Length_of_Service_(Years)','Bonus_Percent']]

In [67]:
df.Bonus_Percent.fillna(0, inplace=True)
df['Salary_Change_%'].fillna(0, inplace = True)
df.dropna(how="all", inplace=True)

In [59]:
df = df[['Salary_Change_%', 'Annual_Salary_If_Full_time',
       'Length_of_Service_(Years)', 'Bonus_Percent', 'Career_Level']]

In [69]:
X = df.ix[:,0:4].values
y = df.ix[:,4].values

In [61]:
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.tools as tls

In [62]:
df.Career_Level.value_counts()

P3    873
P4    573
P2    568
P1    499
P5    148
P6     10
Name: Career_Level, dtype: int64

In [63]:
df.Annual_Salary_If_Full_time.min()

37440.0

# plotting histograms

In [64]:
traces = []

legend = {0:False, 1:False, 2:False, 3:True, 4:True}#, 5:True, 6:True}

colors = {'P1': 'rgb(31, 119, 180)', 
          'P2': 'rgb(255, 127, 14)', 
          'P3': 'rgb(44, 160, 44)',
          'P4': 'rgb(99, 66, 77)',
          'P5': 'rgb(170, 180, 70)',
          'P6': 'rgb(127, 255, 14)'}

for col in range(4):
    for key in colors:
        traces.append(Histogram(x=X[y==key, col], 
                        opacity=0.75,
                        xaxis='x%s' %(col+1),
                        marker=Marker(color=colors[key]),
                        name=key,
                        showlegend=legend[col]))

data = Data(traces)

layout = Layout(barmode='overlay',
                xaxis=XAxis(domain=[16, 3050], title='Salary Change'),
                xaxis2=XAxis(domain=[37440.0, 312000.0], title='Annual Sal'),
                xaxis3=XAxis(domain=[0.016427454, 42.152846964], title='Length of Service'),
                xaxis4=XAxis(domain=[0, 0.2], title='Bonus Percent'),
                yaxis=YAxis(title='count'),
                title='Distribution of the different Career Levels in Professional Band')

fig = Figure(data=data, layout=layout)
py.iplot(fig)


In [70]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)


In [71]:
import numpy as np
mean_vec = np.mean(X_std, axis=0)
cov_mat = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1)
print('Covariance matrix \n%s' %cov_mat)

Covariance matrix 
[[ 1.00037453 -0.09060185  0.00970251 -0.04654444]
 [-0.09060185  1.00037453  0.24781809  0.47516874]
 [ 0.00970251  0.24781809  1.00037453  0.18725347]
 [-0.04654444  0.47516874  0.18725347  1.00037453]]


In [72]:
cov_mat = np.cov(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)


Eigenvectors 
[[-0.13027453  0.9445929  -0.29170081 -0.07538858]
 [ 0.64574492 -0.03587104 -0.21546054 -0.7316444 ]
 [ 0.43028783  0.32613886  0.83335166  0.11836739]
 [ 0.61716646  0.00953771 -0.41714794  0.66708485]]

Eigenvalues 
[ 1.63792416  1.00669516  0.8391729   0.51770591]


In [73]:
cor_mat1 = np.corrcoef(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat1)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)


Eigenvectors 
[[-0.13027453  0.9445929  -0.29170081 -0.07538858]
 [ 0.64574492 -0.03587104 -0.21546054 -0.7316444 ]
 [ 0.43028783  0.32613886  0.83335166  0.11836739]
 [ 0.61716646  0.00953771 -0.41714794  0.66708485]]

Eigenvalues 
[ 1.63731093  1.00631826  0.83885872  0.51751209]


In [74]:
cor_mat2 = np.corrcoef(X.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat2)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)


Eigenvectors 
[[-0.13027453  0.9445929  -0.29170081 -0.07538858]
 [ 0.64574492 -0.03587104 -0.21546054 -0.7316444 ]
 [ 0.43028783  0.32613886  0.83335166  0.11836739]
 [ 0.61716646  0.00953771 -0.41714794  0.66708485]]

Eigenvalues 
[ 1.63731093  1.00631826  0.83885872  0.51751209]


In [75]:
u,s,v = np.linalg.svd(X_std.T)
u


array([[-0.13027453, -0.9445929 ,  0.29170081, -0.07538858],
       [ 0.64574492,  0.03587104,  0.21546054, -0.7316444 ],
       [ 0.43028783, -0.32613886, -0.83335166,  0.11836739],
       [ 0.61716646, -0.00953771,  0.41714794,  0.66708485]])

In [76]:
for ev in eig_vecs:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))
print('Everything ok!')

Everything ok!


In [77]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort()
eig_pairs.reverse()

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])


Eigenvalues in descending order:
1.63731093441
1.00631826365
0.838858716125
0.517512085812


In [78]:
tot = sum(eig_vals)
var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

trace1 = Bar(
        x=['PC %s' %i for i in range(1,5)],
        y=var_exp,
        showlegend=False)

trace2 = Scatter(
        x=['PC %s' %i for i in range(1,5)], 
        y=cum_var_exp,
        name='cumulative explained variance')

data = Data([trace1, trace2])

layout=Layout(
        yaxis=YAxis(title='Explained variance in percent'),
        title='Explained variance by different principal components')

fig = Figure(data=data, layout=layout)
py.iplot(fig)


In [82]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(4,1), 
                      eig_pairs[1][1].reshape(4,1)))

print('Matrix W:\n', matrix_w)


('Matrix W:\n', array([[-0.13027453,  0.9445929 ],
       [ 0.64574492, -0.03587104],
       [ 0.43028783,  0.32613886],
       [ 0.61716646,  0.00953771]]))


In [83]:
Y = X_std.dot(matrix_w)

In [85]:
traces = []

for name in df.Career_Level.unique().tolist():

    trace = Scatter(
        x=Y[y==name,0],
        y=Y[y==name,1],
        mode='markers',
        name=name,
        marker=Marker(
            size=12,
            line=Line(
                color='rgba(217, 217, 217, 0.14)',
                width=0.5),
            opacity=0.8))
    traces.append(trace)


data = Data(traces)
layout = Layout(showlegend=True,
                scene=Scene(xaxis=XAxis(title='PC1'),
                yaxis=YAxis(title='PC2'),))

fig = Figure(data=data, layout=layout)
py.iplot(fig)
